# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 720e495644de1207cabb6224f95c8c126492281dbd75ed99b57f11ffbbcd3f011365f5f7cf390224f3639efe4bcd2818018ced03a3b29c1df7d2226f6ce3d32a

test:
  secret_key_base: c0da9bf4654f3770dd7094e75ec02a6f560f543b088a6b5f714bd56e1b71f9fef9924e972b3790d224f2a108ba970f0931a3312d55079bb21f02ca3e55ed5bd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
